{
 "title": "Project SRSA Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Last Pressure Value",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"PROJECTB\")\r\n |> range(start: -1h)\r\n |> filter(fn: (r) => (r._measurement == \"18_pressure\") and (r._field ==\"value\"))\r\n |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "Pressure History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "targets": [
    {
     "query": "from(bucket: \"PROJECTB\")\r\n |> range(start: -1h)\r\n |> filter(fn: (r) => (r._measurement == \"18_pressure\") and (r._field ==\"value\"))\r\n |> yield(name: \"_results\")"
    },
    {
     "query": "from(bucket: \"PROJECTB\")\r\n |> range(start: -1h)\r\n |> filter(fn: (r) => (r._measurement == \"18_pressure\") and (r._field ==\"value\"))\r\n |> movingAverage(n:30)\r\n |> yield(name: \"average\")"
    }
   ]
  },
  {
   "title": "Last Temperature value",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"PROJECTB\")\r\n |> range(start: -1h)\r\n |> filter(fn: (r) => (r._measurement == \"18_temperature\") and (r._field ==\"value\"))\r\n |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "Temperature History",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"PROJECTB\")\r\n |> range(start: -1h)\r\n |> filter(fn: (r) => (r._measurement == \"18_temperature\") and (r._field ==\"value\"))\r\n |> yield(name: \"_results\")"
    },
    {
     "query": "from(bucket: \"PROJECTB\")\r\n |> range(start: -1h)\r\n |> filter(fn: (r) => (r._measurement == \"18_temperature\") and (r._field ==\"value\"))\r\n |> movingAverage(n:30)\r\n |> yield(name: \"average\")"
    }
   ]
  },
  {
   "title": "Last Luminosity value",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"PROJECTB\")\r\n |> range(start: -1h)\r\n |> filter(fn: (r) => (r._measurement == \"18_luminosity\") and (r._field ==\"value\"))\r\n |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "Luminosity history",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "query": "from(bucket: \"PROJECTB\")\r\n |> range(start: -1h)\r\n |> filter(fn: (r) => (r._measurement == \"18_luminosity\") and (r._field ==\"value\"))\r\n |> yield(name: \"_results\")\r\n"
    },
    {
     "query": "from(bucket: \"PROJECTB\")\r\n |> range(start: -1h)\r\n |> filter(fn: (r) => (r._measurement == \"18_luminosity\") and (r._field ==\"value\"))\r\n |> movingAverage(n:30)\r\n |> yield(name: \"average\")\r\n"
    }
   ]
  },
  {
   "title": "Last Value Humidity Sensor 1",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"PROJECTB\")\r\n |> range(start: -1h)\r\n |> filter(fn: (r) => (r._measurement == \"sensor_data_hum_1\") and (r._field ==\"value\"))\r\n |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "Humidity 1 History",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"PROJECTB\")\r\n |> range(start: -1h)\r\n |> filter(fn: (r) => (r._measurement == \"sensor_data_hum_1\") and (r._field ==\"value\"))\r\n |> yield(name: \"_results\")"
    },
    {
     "query": "from(bucket: \"PROJECTB\")\r\n |> range(start: -1h)\r\n |> filter(fn: (r) => (r._measurement == \"sensor_data_hum_1\") and (r._field ==\"value\"))\r\n |> movingAverage(n:30)\r\n |> yield(name: \"average\")"
    }
   ]
  },
  {
   "title": "Last Value Humidity Sensor 2",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"PROJECTB\")\r\n |> range(start: -1h)\r\n |> filter(fn: (r) => (r._measurement == \"sensor_data_hum_2\") and (r._field ==\"value\"))\r\n |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "Humidity 2 History",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"PROJECTB\")\r\n |> range(start: -1h)\r\n |> filter(fn: (r) => (r._measurement == \"sensor_data_hum_2\") and (r._field ==\"value\"))\r\n |> yield(name: \"_results\")"
    },
    {
     "query": "from(bucket: \"PROJECTB\")\r\n |> range(start: -1h)\r\n |> filter(fn: (r) => (r._measurement == \"sensor_data_hum_2\") and (r._field ==\"value\"))\r\n |> movingAverage(n:30)\r\n |> yield(name: \"average\")"
    }
   ]
  },
  {
   "title": "Last Energy Value(Off Peak)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"PROJECTB\")\r\n |> range(start: -1h)\r\n |> filter(fn: (r) => (r._measurement == \"off_peak\") and (r._field ==\"value\"))\r\n |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "Sensor Energy(off_peak)",
   "type": "timeseries",
   "description": "0.10EURO/Kwh",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"PROJECTB\")\r\n |> range(start: -1h)\r\n |> filter(fn: (r) => (r._measurement == \"off_peak\") and (r._field ==\"value\"))\r\n |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "Last Energy Value(Peak)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"PROJECTB\")\r\n |> range(start: -1h)\r\n |> filter(fn: (r) => (r._measurement == \"peak\") and (r._field ==\"value\"))\r\n |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "Sensor energy(peak)",
   "type": "timeseries",
   "description": "0.20euro/Kw",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"PROJECTB\")\r\n |> range(start: -1h)\r\n |> filter(fn: (r) => (r._measurement == \"peak\") and (r._field ==\"value\"))\r\n |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "Total Cost( Peak)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "euros/Kwh" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"PROJECTB\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"peak\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: r._value,\r\n      total_cost: r._value * 0.2  // Assuming a predefined cost value of 0.2\r\n    }))\r\n  |> yield(name: \"data\")"
    }
   ]
  },
  {
   "title": "Variação da energia ao longo ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 9, "y": 68 },
   "targets": [
    {
     "query": "from(bucket: \"PROJECTB\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => (r._measurement == \"peak\" or r._measurement == \"off_peak\"))\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)  // Adjust the aggregation interval as per your data resolution\r\n  |> yield(name: \"value\")"
    }
   ]
  },
  {
   "title": "Total Cost(Off_Peak)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "euros/KwH" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"PROJECTB\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"off_peak\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: r._value,\r\n      total_cost: r._value * 0.1  // Assuming a predefined cost value of 0.1\r\n    }))\r\n  |> yield(name: \"data\")"
    }
   ]
  }
 ]
}